language: python
python:
  - "2.7.14"
install: # command to install dependencies
  - "pip install -r requirements.txt"
# command to run tests
script: python server/tests/*

notifications:
  email:
       jamesleahy314@gmail.com

sudo: false
